export const RECEIVE_ACCOUNTS_EXECUTION = 'RECEIVE_ACCOUNTS_EXECUTION'
export const RECEIVE_ACCOUNTS_SETTING = 'RECEIVE_ACCOUNTS_SETTING'
export const ACCOUNT_SELECTED = 'ACCOUNT_SELECTED'
export const FETCH_OFF_ADS = 'FETCH_OFF_ADS'
